name: My Workflow

on:
  workflow_dispatch:
  
env:
  TRIGGER_COUNT: 0

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@v3.3.1
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**yarn.lock') }}-v5

      - name: Install dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Update package versions
        run: |
          git config user.email "alex.naduev@gmail.com"        
          git config user.name "GitHub Actions"        
          npx lerna version patch --include-merged-tags --yes
